-- PageLog: run once in Supabase Dashboard > SQL Editor.
create table if not exists public.pagelog_users (
  id bigint generated by default as identity primary key,
  username text not null unique check (char_length(username) between 3 and 40),
  display_name text not null check (char_length(display_name) between 1 and 80),
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.pagelog_sessions (
  token_hash text primary key,
  user_id bigint not null references public.pagelog_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.pagelog_notes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.pagelog_users(id) on delete cascade,
  book_title text not null check (char_length(book_title) between 1 and 120),
  author text not null check (char_length(author) between 1 and 80),
  read_date date not null,
  rating smallint not null check (rating between 1 and 5),
  memo text not null check (char_length(memo) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists idx_pagelog_sessions_user_id on public.pagelog_sessions(user_id);
create index if not exists idx_pagelog_sessions_expires_at on public.pagelog_sessions(expires_at);
create index if not exists idx_pagelog_notes_user_read_date on public.pagelog_notes(user_id, read_date desc, id desc);

alter table public.pagelog_users enable row level security;
alter table public.pagelog_sessions enable row level security;
alter table public.pagelog_notes enable row level security;

revoke all on public.pagelog_users from anon, authenticated;
revoke all on public.pagelog_sessions from anon, authenticated;
revoke all on public.pagelog_notes from anon, authenticated;

grant select, insert, update, delete on public.pagelog_users to service_role;
grant select, insert, update, delete on public.pagelog_sessions to service_role;
grant select, insert, update, delete on public.pagelog_notes to service_role;
grant usage, select on all sequences in schema public to service_role;
